version: '3'

volumes:
  mariadb_master_volume:
    driver: 'local'
  mariadb_slave_volume:
    driver: 'local'

services:
  mariadb_master:
    build: ./mariadb/
    volumes:
      - mariadb_master_volume:/var/lib/mysql
      - ./scripts:/var/scripts
      - ./data:/var/data
      - ./mariadb/master.cnf:/etc/mysql/conf.d/master.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "mariadb_master"
    ports:
      - "13306:3306"

  mariadb_slave:
    build: ./mariadb/
    volumes:
      - mariadb_slave_volume:/var/lib/mysql
      - ./scripts:/var/scripts
      - ./data:/var/data
      - ./mariadb/slave.cnf:/etc/mysql/conf.d/slave.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "mariadb_slave"
    ports:
      - "13307:3306"

