version: '3'

volumes:
  mariadb_lock_volume:
    driver: 'local'

services:
  mariadb_lock:
    build: ./mariadb/
    volumes:
      - mariadb_lock_volume:/var/lib/mysql
      - ./scripts:/var/scripts
      - ./data:/var/data
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "mariadb_lock"
    ports:
      - "13306:3306"

