version: '3'

volumes:
  after_destroy_callback_db_volume:
    driver: 'local'

  after_destroy_callback_gem_volume:
    driver: 'local'

services:
  after_destroy_callback_front:
    build: ../../front/
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ../../front/scripts:/var/scripts
    environment:
      APP_HOST:
      APP_PORT:
    container_name: "after_destroy_callback_front"
    command: /var/scripts/start.sh

  after_destroy_callback_db:
    build: ../../db/
    volumes:
      - after_destroy_callback_db_volume:/var/lib/mysql
      - ../../db/scripts:/var/scripts
    environment:
      DB_NAME:
      DB_HOST:
      DB_USER:
      DB_PASS:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "after_destroy_callback_db"
    ports:
      - "3306:3306"

  after_destroy_callback_web:
    build: ../../web/
    volumes:
      - ../../web/myapp:/myapp
      - ../../web/scripts:/var/scripts
      - after_destroy_callback_gem_volume:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DB_NAME:
      DB_HOST:
      DB_USER:
      DB_PASS:
      BUNDLE_APP_CONFIG: /myapp/.bundle
      RAILS_PRODUCTION_MODE:
    container_name: "after_destroy_callback_web"
    command: /var/scripts/entry_point.sh
